### PR TITLE
Adapt theme for Cinnamon 3.2

### PR DESCRIPTION
**Pull request by germanfr**
Some classes changed their name and added vertical panels assets.

### CODE REVIEW

**Comment by zagortenay333** [comment]
Thx but you didn't have to :smile: . I'm waiting for mint 18.1 to update the themes.

**Comment by germanfr** [comment]
I thought the theme was no longer under maintenance. Btw there are still some issues with vertical panels.

**Comment by zagortenay333** [comment]
No worries, I'll fix them when I update.

**Comment by germanfr** [comment]
Oh if you still on 3.0.x, it would be great to check if I broke something there. I tried to maintain compatibility, but I can't know for sure because I already got 3.2 on Arch (also that's why I wanted to port it asap, to not have it broken).

**Comment by zagortenay333** [comment]
I tagged a safe commit for 2.8 and 3.0 https://github.com/zagortenay333/new-minty/releases

**Comment by germanfr** [comment]
I managed to test it on 3.0.7 and it had some issues. I fixed them on #7 and now is fully compatible.

**Pull request merged**
